"""Markdown Validation & Triage Report renderer.

Design intent: the console render is for the demo; the markdown report is
the artifact — it gets attached to the incident ticket / PagerDuty note /
post-mortem. Structure follows the "3am on-call" rule: WHAT broke, HOW BAD,
WHAT FIRST, in that order, with evidence (retrieved runbook chunks) cited
per verdict so the next engineer can audit the reasoning.
"""
from __future__ import annotations

from agent.schemas import TriageReport

_ACTION_EMOJI = {
    "DRAIN_NODE": "🟥",
    "DRAIN_NODE_AND_OPEN_RMA": "🟥",
    "DRAIN_NODE_AND_ESCALATE": "🟥",
    "RESET_GPU": "🟧",
    "CHECK_APPLICATION": "🟨",
    "MONITOR": "🟩",
    "IGNORE_EVENT": "⬜",
    "NEEDS_HUMAN_REVIEW": "⬜",
}


def render_markdown(report: TriageReport) -> str:
    lines = [
        "# Validation & Triage Report",
        "",
        f"- **Generated:** {report.generated_at}",
        f"- **Data:** {'SIMULATED (synthetic telemetry — demo mode)' if report.simulated else 'REAL hardware telemetry'}",
        f"- **Nodes scanned:** {report.node_count}  |  "
        f"**Events:** {report.event_count}  |  "
        f"**XID findings:** {len(report.verdicts)}",
        "",
    ]

    # Executive summary: worst-first action list.
    actions: dict[str, int] = {}
    for v in report.verdicts:
        actions[v.action] = actions.get(v.action, 0) + 1
    if actions:
        lines += ["## Recommended actions (summary)", ""]
        for action, n in sorted(actions.items(),
                                key=lambda kv: -_severity_rank(kv[0])):
            emoji = _ACTION_EMOJI.get(action, "⬜")
            lines.append(f"- {emoji} **{action}** × {n}")
        lines += [""]

    lines += ["## Findings", ""]
    if not report.verdicts:
        lines.append("No XID events found. Fleet looks healthy (in this sample).")
    for i, v in enumerate(report.verdicts, 1):
        f = v.finding
        label = f.name or f"UNKNOWN XID {f.xid_code}"
        emoji = _ACTION_EMOJI.get(v.action, "⬜")
        lines += [
            f"### {i}. {emoji} {label} (XID {f.xid_code})",
            "",
            f"- **Severity:** {f.severity}  |  **Node:** `{f.node_id}`  |  "
            f"**GPU:** {f.gpu_index}  |  **Time:** {f.timestamp}",
            f"- **Recommended action:** `{v.action}` "
            f"(confidence {v.confidence:.2f})",
            f"- **Rationale:** {v.rationale}",
        ]
        if v.evidence:
            lines += ["- **Runbook evidence:**"]
            for chunk_id, text in v.evidence:
                first_line = text.strip().split("\n")[0]
                lines.append(f"  - `{chunk_id}` — {first_line}")
        lines += [""]

    counts = report.counts_by_severity()
    lines += ["## Severity breakdown", "",
              ", ".join(f"{k}: {v}" for k, v in sorted(counts.items())) or "n/a",
              "", "---",
              "_Generated by AI-Node-Sentinel (demo mode: all telemetry "
              "synthetic). Triage rules are heuristic defaults — validate "
              "against your site runbook before operational use._"]
    return "\n".join(lines)


def _severity_rank(action: str) -> int:
    """Order the action summary worst-first."""
    order = {"DRAIN_NODE_AND_OPEN_RMA": 5, "DRAIN_NODE_AND_ESCALATE": 5,
             "DRAIN_NODE": 4, "RESET_GPU": 3, "NEEDS_HUMAN_REVIEW": 2,
             "CHECK_APPLICATION": 1, "MONITOR": 0}
    return order.get(action, -1)
